### ISSUE TITLE
FuncWithFallback with other signatures

### ISSUE THREAD

**Issue by aveXcaesar** [icarus-consulting/Yaapii.Atoms#101]
### Bug Report or Feature Request (mark with an x)
- [ ] bug report -> please search issues before submitting
- [x] feature request

### Expected Behavior
We need a FuncWithFallback with the following signatures:
```csharp
FuncWithFallback<In>
FuncWithFallback<Out>
FuncWithFallback
```

### Actual Behavior
We have a 
```csharp
FuncWithFallback<In, Out>
```

**Comment by Meerownymous** [comment]
@aveXcaesar not correct, we need 
```
FuncWithFallback<Out>
ActionWithFallback
ActionWithFallback<In>
BiFuncWithFallback<In1, In2, Out>
```
