### ISSUE TITLE
Contains of an empty list should not throw an exception!

### ISSUE THREAD

**Issue by ICACLE** [icarus-consulting/Yaapii.Atoms#103]
### Bug Report or Feature Request (mark with an x)
- [x] bug report -> please search issues before submitting
- [ ] feature request

### Expected Behavior
Contains of an emty list returns false

### Actual Behavior
Contains of an emty list throws an exception

### Mention any other details that might be useful

https://github.com/icarus-consulting/Yaapii.Atoms/blob/58d8d01adcd9816a4162eaa4f560ce2cad1603ec/src/Yaapii.Atoms/Enumerator/ContainsEnumerator.cs#L59

**Comment by Meerownymous** [comment]
Closes via pr #104
