### ISSUE TITLE
Class for Linq OfType

### ISSUE THREAD

**Issue by ICACLE** [icarus-consulting/Yaapii.Atoms#105]
### Bug Report or Feature Request (mark with an x)
- [ ] bug report -> please search issues before submitting
- [x] feature request

### Expected Behavior
A class wich implements only the IEnumerable but not the IEnumerable\<T\> interface can be converted to a IEnumerable\<T\> like OfType\<T\> or Cast\<T\> from linq does.

### Actual Behavior
A class wich implements only the IEnumerable but not the IEnumerable\<T\> interface can not be converted.

**Comment by Meerownymous** [comment]
We do not want to use casting. And we do not want to check types. Lets not integrate this into Atoms.

**Comment by ICACLE** [comment]
@Meerownymous  So i will still use .OfType to my problem...
I thougt we could implement a ctor in EnumerableOf<T> which takes a IEnumerable
If the type is not matching we get an exception.

**Comment by Meerownymous** [comment]
We can do that, if there is no other solution (by finding abother design for example)... My point was, I just don‘t think it belongs into Atoms, I think it belongs into adapter modules.

**Comment by Meerownymous** [comment]
Closed.

**Comment by koeeenig** [comment]
I agree with @Meerownymous
