### ISSUE TITLE
Fix Warning conflicts between different versions of the same dependent assembly.

### ISSUE THREAD

**Issue by aveXcaesar** [icarus-consulting/Yaapii.Atoms#109]
### Bug Report or Feature Request (mark with an x)
- [x] bug report -> please search issues before submitting
- [ ] feature request

### Expected Behavior
No Warnings

### Actual Behavior
Warning:

> MSB3277	Found conflicts between different versions of the same dependent assembly that could not be resolved.  These reference conflicts are listed in the build log when log verbosity is set to detailed.

in Yaapii.Atoms.Tests	

### Mention any other details that might be useful
Set MSBuild project build output verbosity to "Detailed" to see details.

**Comment by Meerownymous** [comment]
Fixed via update of xunit nugets, see https://github.com/Microsoft/vstest/issues/393
