### ISSUE TITLE
Ctor in EnumerableOf class should accept himself to add an element

### ISSUE THREAD

**Issue by aveXcaesar** [icarus-consulting/Yaapii.Atoms#115]
### Bug Report or Feature Request (mark with an x)
- [ ] bug report -> please search issues before submitting
- [x] feature request

### Expected Behavior
To add a new element it should be possible:
```csharp
var x = new Enumerable<int>();
x = new Enumerable<int>(x, 5);
```
Then remove Joined class.

Do the same for:
- CollectionOf
- ListOf

### Actual Behavior
Currently we have to use Joined:
```csharp
var x = new Enumerable<int>();
x = new Joined<int>(x, 5);
```

**Comment by koeeenig** [comment]
We think we stick with Joined because it is more declarative and therefore what is happening is more clear.
Closing.
