### ISSUE TITLE
Filtered classes should throw IllegalArgumentException when params < 2

### ISSUE THREAD

**Issue by Meerownymous** [icarus-consulting/Yaapii.Atoms#117]
### Bug Report or Feature Request (mark with an x)
- [x] bug report -> please search issues before submitting
- [ ] feature request

### Expected Behavior
Enumerable.Filtered has a tor which accepts params. In that case, when params is empty, it throws a IllegalArgumentException("Need at least two elements to filter").

**This must NOT be thrown when an empty enumerable is passed to the filter (the other ctor which accepts enumerable)**

### Mention any other details that might be useful

This should also be fixed in Collection.Filtered and other Filtered classes, if bug is there too.

**Comment by ICACLE** [comment]
@Meerownymous  I think we should edid the ctor to force at least 2 items are given, instead of throwing an exception is params invalid

**Comment by Meerownymous** [comment]
Good solution!
