### ISSUE TITLE
Make FailEmpty non generic

### ISSUE THREAD

**Issue by Meerownymous** [icarus-consulting/Yaapii.Atoms#123]
### Bug Report or Feature Request (mark with an x)
- [ ] bug report -> please search issues before submitting
- [x] feature request

### Expected Behavior
FailEmpty is non generic.

### Actual Behavior
FailEmpty is generic.

### Mention any other details that might be useful
FailEmpty can work congeneric, because it just needs to count the elements of a enumerable. The C# Enumerable<T> always implements Enumerable nongeneric. That means you can simply use the congeneric interface for this issue.

**Comment by aveXcaesar** [comment]
@Meerownymous 
What is congeneric?
Do it mean we have a generic and an not generic version of the class coexisting?

**Comment by Meerownymous** [comment]
Autocorrect... Non generic is meant...

**Comment by aveXcaesar** [comment]
Non generic not needed. We would like to use this decorator in the same way as the decorated classes. The decorated classes are generic.
