### ISSUE TITLE
Writing a file with atoms is not easy to handle

### ISSUE THREAD

**Issue by ICACLE** [icarus-consulting/Yaapii.Atoms#124]
### Bug Report or Feature Request (mark with an x)
- [ ] bug report -> please search issues before submitting
- [x] feature request

### Expected Behavior
Having a simple Class to write a file (as simple as File.WriteAllText())

### Actual Behavior
Writing a file is complex and easy to make as mistake.

### Steps to reproduce the behavior
```csharp
new LengthOf(
    new TeeInput(
        new InputOf(program),
        new WriterAsOutput(
            new WriterTo(
                new Uri(filePath))))).Value();
``` 

### Mention any other details that might be useful

If i need more than 5 min to do a simple thing like 'File.WriteAllText()' with atoms is not an improvment.

**Comment by Meerownymous** [comment]
This would be something for another library... Atoms need to be primitive and stay cohesive.
