### ISSUE TITLE
Create a mapping table of Atom classes and LinQ Methods

### ISSUE THREAD

**Issue by ICACLE** [icarus-consulting/Yaapii.Atoms#137]
### Bug Report or Feature Request (mark with an x)
- [ ] bug report -> please search issues before submitting
- [x] feature request

### Expected Behavior
Have a mapping table to get the Atom class which replaces a Linq Methode

### Mention any other details that might be useful
Edit Readme.md of 'Yaapii.Atoms' or add wiki entry.

**Comment by aveXcaesar** [comment]
I started in branch i137-docMappingTableOfLinQ. Please continue here.
