### ISSUE TITLE
JoinedText() ignores some characters

### ISSUE THREAD

**Issue by icaOBU** [icarus-consulting/Yaapii.Atoms#144]
### Bug Report or Feature Request (mark with an x)
- [x] bug report -> please search issues before submitting
- [ ] feature request

### Expected Behavior
new JoinedText("{0}.*", Path.GetFileNameWithoutExtension(fileInfo.Name)).AsString() returns "filename.*"

### Actual Behavior
returns only "filename"

**Comment by Meerownymous** [comment]
You should use FormattedText, JoinedText joins texts - you want to format one.
