### ISSUE TITLE
Enumerable.Replaced() should accept an index

### ISSUE THREAD

**Issue by aveXcaesar** [icarus-consulting/Yaapii.Atoms#145]
### Bug Report or Feature Request (mark with an x)
- [ ] bug report -> please search issues before submitting
- [x] feature request

### Expected Behavior
I need a ctor to replace an entity at a given index like this:
```csharp
Replaced(IEnumerable<T> origin, int index, T replacement)
```

### Actual Behavior
We have only a matching function.

**Comment by Meerownymous** [comment]
Can you give an example what you need this for? Can‘t it be solved using Mapped?

**Comment by aveXcaesar** [comment]
I can't remember the code place where I did need it.
I did know the index at wich I would replace an entity and that's the reason for this issue.
How can Mapped help me to enter the index?

**Comment by Meerownymous** [comment]
Mapped provides an index. That would do the trick. Just return your replacement at the desired index.

**Comment by aveXcaesar** [comment]
Ah, okay:
```csharp
var list = new ListOf<int>(1, 2, 3, 4);
var replacedList = 
	new Mapped<int, int>(
		(item, index) => index == 1 ? 99 : item,
		list
	);
```
But using `Replaced()` is more intuitive as using `Mapped()` in this situation. I expect to use `Replaced()` instead of using `Mapped()` to replace an item at an certain index.
Do you agree with me?
