### ISSUE TITLE
Make a sourcecode based Atoms package

### ISSUE THREAD

**Issue by Meerownymous** [icarus-consulting/Yaapii.Atoms#157]
### Bug Report or Feature Request (mark with an x)
- [ ] bug report -> please search issues before submitting
- [x] feature request

### Expected Behavior
We have two packages of Atoms: One is linking the dll files, on is linking the source code files.

### Actual Behavior
We have only the library based version

**Comment by Meerownymous** [comment]
Closed due to inactivity.

**Comment by aveXcaesar** [comment]
This is already done
