### ISSUE TITLE
Add documentation to Fail class wich exception type is be thrown

### ISSUE THREAD

**Issue by ICACLE** [icarus-consulting/Yaapii.Atoms#158]
### Bug Report or Feature Request (mark with an x)
- [ ] bug report -> please search issues before submitting
- [x] feature request

### Expected Behavior
We can see in the comment wich exception type is be thrown

### Actual Behavior
Have to look in Atoms code to get the exception type thrown by fail classes

**Comment by Meerownymous** [comment]
What do you mean? Which comment?

**Comment by ICACLE** [comment]
I used a fail When class and wanted to write a test where i expected a exception is thrown, but i have to open the atoms and read the code of the class to get the type of exception wich will be thrown... I think it is good if u can read this type in the comments of the class/ctor/methode.

**Comment by Meerownymous** [comment]
Ah I see, by comment I think of inline comments but you mean xmldoc - class documentation. Alright then.
