### ISSUE TITLE
Make LengthOf sticky 

### ISSUE THREAD

**Issue by icaOBU** [icarus-consulting/Yaapii.Atoms#165]
### Bug Report or Feature Request (mark with an x)
- [ ] bug report -> please search issues before submitting
- [ ] feature request

### Expected Behavior
If `LenghtOf(enumeration)` is called one time, the function doesn´t have to iterate again throgh the Enumeration every time when `.Value()` is called. This is very time consuming (e.g. the creation of the threeJsJson. There is the LengthOf used in a for-loop and is called 1.87Mio times). Alternative link to `enumerable.Length`

### Actual Behavior
`LengthOf` iterates every time through the enumerable

**Comment by Meerownymous** [comment]
Thought about it and had a look at the original. LengthOf is not supposed to be used as a scalar whose value is being re-used over and over.

LengthOf has two purposes:
- Read every Byte in a Stream
- return the number

Making it sticky would take away the decision if it should re-iterate from the user. Solution is to improve the XML header docs but leave it as it is.

**Comment by Meerownymous** [comment]
Done.
