### ISSUE TITLE
Trim classes should accept chars and string

### ISSUE THREAD

**Issue by Meerownymous** [icarus-consulting/Yaapii.Atoms#186]
### Expected Behavior
We can do this:
```csharp
new TrimmedLeftText("Foo", "FooStringBlabla").AsString();
new TrimmedLeftText(new char[]{ ' ', 'F', 'O' } , "FooStringBlabla").AsString();
```
This should be done for TrimmedLeftText, TrimmedRightText and TrimmedText.

**Comment by pz1337** [comment]
@Meerownymous What do you mean with 

> new TrimmedLeftText("Foo", "FooStringBlabla").AsString();

?
The second "o" is confusing. Trim left or remove string from start?
Trim:
"Fo", "FooString" --> "String"
"Fo", "FooFooString" --> "String"
"oF", "FooFooString" --> "String"
I understand Trim as a trimming of chars not of strings.

**Comment by Meerownymous** [comment]
```csharp
"Fo", "FooString" --> "oString"
"Fo", "FooFooString" --> "oFooString"
"oF", "FooFooString" --> "FooFooString"
```

**Comment by koeeenig** [comment]
@pz1337 are you still working on this issue? if not please unassign

**Comment by pz1337** [comment]
I do.
