### ISSUE TITLE
Port class TailInput and TailInputStream

### ISSUE THREAD

**Issue by Meerownymous** [icarus-consulting/Yaapii.Atoms#198]
### Expected Behavior
We have these classes:
https://github.com/yegor256/cactoos/blob/master/src/main/java/org/cactoos/io/TailOf.java

**Comment by jussen** [comment]
I've started the implementation and `TailInput` is testable - `TailInputStream` needs an implementation at the marked methods (comments prepared).
I won't be able to finish the issue within the next 3 days. Feel free to finish it.

For further details see branch `i198-tailinput-implementation`
