### ISSUE TITLE
TeeInput does not consider Uri type

### ISSUE THREAD

**Issue by jussen** [icarus-consulting/Yaapii.Atoms#214]
### Expected Behavior
Web content should be written to the given file.

### Actual Behavior
Code throws an UnauthorizedAccessException due to an access of D drive.
`Message: System.UnauthorizedAccessException : Access to the path 'D:\' is denied.`

### Steps to reproduce the behavior
```csharp
var directoryPath = @"%temp%\Yaapii.Atoms.Temp-Files";
System.IO.Directory.CreateDirectory(directoryPath);

new LengthOf(
    new TeeInput(
        new Uri("http://www.spiegel.de"),
        new Uri($@"file:///{directoryPath}\www.spiegel.de.txt")
        )
    ).Value();
```

**Comment by DFU398** [comment]
pr #315 addresses this, but
```
var directoryPath = @"%temp%\Yaapii.Atoms.Temp-Files";
System.IO.Directory.CreateDirectory(directoryPath);

new LengthOf(
    new TeeInput(
        new Uri("http://www.spiegel.de"),
        new Uri($@"file:///{directoryPath}\www.spiegel.de.txt")
        )
    ).Value();
```
still wouldn't work, because windows environment variables like %temp% won't be resolved in this context. If you use
```
var directoryPath = Path.GetTempPath() + "Yaapii.Atoms.Temp-Files";
```
instead, then it should work now.

**Comment by Meerownymous** [comment]
Done.
