### ISSUE TITLE
TextOf ctor does not use given encoding

### ISSUE THREAD

**Issue by MSE1188** [icarus-consulting/Yaapii.Atoms#218]
### Expected Behavior
The TextOf(IBytes bytes, Encoding encoding) - ctor does not use the given Encoding to encode the bytes

**Comment by Meerownymous** [comment]
Correct, this ctor is wrong (ignores encoding)

https://github.com/icarus-consulting/Yaapii.Atoms/blob/1b46a6bff45401009568320a4174b029d96dc437/src/Yaapii.Atoms/Text/TextOf.cs#L233
