### ISSUE TITLE
Remove CompareTo methods from classes which implement IText!?

### ISSUE THREAD

**Issue by ICACLE** [icarus-consulting/Yaapii.Atoms#231]
### Expected Behavior
If i want to compare texts i use the ComparableText class.
There is no method in a class wich is not defined by an interface.

### Actual Behavior
Some Text classes implements a CompareTo methode.

### Mention any other details that might be useful
Maybe we can remove the Equals methode (IEquatable<IText> interface) also and Write a Class TextEquals?

**Comment by Meerownymous** [comment]
Cactoos solved this by introducing a class [ComparableText](https://github.com/yegor256/cactoos/blob/master/src/main/java/org/cactoos/text/ComparableText.java) which is the only class that can be used to compare. Lets adopt this.
