### ISSUE TITLE
Move BytesOf and EmptyBytes to Yaapii.Atoms.Bytes

### ISSUE THREAD

**Issue by aveXcaesar** [icarus-consulting/Yaapii.Atoms#255]
### Expected Behavior

`BytesOf()` and `EmptyBytes()` are located at Yaapii.Atoms.Bytes namespace

### Actual Behavior

`BytesOf()` and `EmptyBytes()` are located at Yaapii.Atoms.IO namespace

### Mention any other details that might be useful

What do you think @icarus-consulting/dop ?

**Comment by pz1337** [comment]
When you think of moving the BytesOf class don't forget to think of moving the other Bytes related classes:

![OtherBytesRelatedClasses](https://user-images.githubusercontent.com/32294625/45417351-4128d980-b682-11e8-897a-7075ea79a439.png)

**Comment by aveXcaesar** [comment]
You are right with `EmtyBytes()`.
The other classes are correct located in IO because theses classes are more related to IO as to Bytes.
I will update the issue
