### ISSUE TITLE
Primitives: CharOf

### ISSUE THREAD

**Issue by Meerownymous** [icarus-consulting/Yaapii.Atoms#26]
We need a Scalar "CharOf" which accepts multiple other types and returns a Char as value.

**Comment by aveXcaesar** [comment]
We have a ScalarOf<char>. Why do we need an dedicated implementation?

**Comment by Meerownymous** [comment]
Yep.

**Comment by aveXcaesar** [comment]
Do you mean an char array or really a simple char?

**Comment by Meerownymous** [comment]
Return type is always a char.
