### ISSUE TITLE
IsWhitespace needs string ctor

### ISSUE THREAD

**Issue by pz1337** [icarus-consulting/Yaapii.Atoms#274]
### Expected Behavior

IsWhitespace class has ctor that takes string.
### Actual Behavior

It doesn't.

**Comment by Meerownymous** [comment]
We should use TextOf, then IsWhiteSpace.

**Comment by pz1337** [comment]
That is what the ctor should do, take string, use TextOf, iirc.
Why should we do things a ctor can do for us?

**Comment by Meerownymous** [comment]
Because if not we need to add all these ctors to all our classes, which is a lot of work and produces code duplication.
