### ISSUE TITLE
BytesOf from int, double, ...

### ISSUE THREAD

**Issue by aveXcaesar** [icarus-consulting/Yaapii.Atoms#279]
### Expected Behavior

`BytesOf` has secondary ctors whos accepts elementary datatypes: int, double, long, float

### Actual Behavior

Ctors missing.

### Mention any other details that might be useful

Currently I build a decorator which is able to take the requested datatypes in my project. `BytesOf` is in the `Yaapii.Atoms.IO` namespace and not in `Yappii.Atoms.Bytes`. I expected it is located in IO namespace but it isn't. Do I have a different view to the object and `BytesOf` is not responsable to elementary datatypes?

**Comment by aveXcaesar** [comment]
@Meerownymous @koeeenig 
what do you think?

**Comment by Meerownymous** [comment]
These ctors should be in InputOf.

**Comment by Meerownymous** [comment]
BytesOf should be moved to Yaapii.Bytes.
