### ISSUE TITLE
Remove unchecked classes

### ISSUE THREAD

**Issue by Meerownymous** [icarus-consulting/Yaapii.Atoms#28]
We can remove IoChecked and IoUnchecked classes.
These classes have been ported, but are irrelevant in .Net: In java, exception throwing has two faces: Checked or Unchecked. In .Net, this is not true.

**Comment by aveXcaesar** [comment]
Can't find IoUnchecked Classes. Do you mean for example UncheckedBiFunc?

**Comment by Meerownymous** [comment]
Yes, sry typo - I meant all classes stating with IoChecked, Checked and Unchecked (if any).
Please see if these classes are used somewhere and remove their usage.
Replace their usage with the corresponding class which does not have the prefix, if needed.
