### ISSUE TITLE
Add ctors to BytesOf

### ISSUE THREAD

**Issue by aveXcaesar** [icarus-consulting/Yaapii.Atoms#293]
### Expected Behavior

`BytesOf` has ctors which accept `int`, `long`, `float`, `double`.

### Actual Behavior

Requested ctors are missing.

### Mention any other details that might be useful

Discussion: #279 

Example for `int`:
```csharp
public BytesOf(int value) : this(
    new ScalarOf<byte[]>(() =>
        BitConverter.GetBytes(value)
    )
)
{ }
```

**Comment by Meerownymous** [comment]
Please adjust the title.
Right now it says "BytesOf accepts..." which is not true. the title is not the "Expected behaviour".

**Comment by aveXcaesar** [comment]
Done
