### ISSUE TITLE
Add merge ctor to StringMap

### ISSUE THREAD

**Issue by aveXcaesar** [icarus-consulting/Yaapii.Atoms#296]
### Expected Behavior

`StringMap` has the following ctor:
```csharp
StringMap(IDictionary<string, string> src, params string[] pairSequence)
```

### Actual Behavior

I can use the `MapOf` class to merge an existing map with new `KeyValuePair`s like this:
```csharp
new MapOf<string, string>(
	existingMap,
	new KeyValuePair<string, string>("hello", "world")
);
```
But I cannot do this with the `StringMap`.

**Comment by Meerownymous** [comment]
No need to define a keyvaluepair, the key + value would be simpler.

**Comment by aveXcaesar** [comment]
That's true. Expected Behavior updated.
