### ISSUE TITLE
Remove KeyValuePair ctor in StringMap

### ISSUE THREAD

**Issue by aveXcaesar** [icarus-consulting/Yaapii.Atoms#297]
### Expected Behavior

The ctor which takes `params KeyValuePair<string, string>[] pairs` is removed.
We can use `StringMap` like as follows:
```csharp
new StringMap();
```

### Actual Behavior

There are two params ctors -> ambiguous

**Comment by Meerownymous** [comment]
StringMap palready has that ctor. It is ambiguous, the one taking KeyValuePair must be removed.

**Comment by aveXcaesar** [comment]
I can't find that ctor in the current master?!

**Comment by Meerownymous** [comment]
Then look again. There are params ctors.

**Comment by aveXcaesar** [comment]
To use the params ctors i have to inject at least one object. But I wont create a empty object. I will call an empty ctor.

**Comment by aveXcaesar** [comment]
Now I got it.
