### ISSUE TITLE
Test fails: Yaapii.Atoms.Tests.IO.WriterToTest

### ISSUE THREAD

**Issue by ICACLE** [icarus-consulting/Yaapii.Atoms#32]
A enconding problem exists in test: public void WritesContentToFile()

**Comment by Meerownymous** [comment]
Fixed by trimming BOM.

**Comment by ICACLE** [comment]
Test still fails on my machine

**Comment by Meerownymous** [comment]
Fixed by using a StreamReader with MemoryStream in TextOf class which removes preamble.
