### ISSUE TITLE
Fix BowAction

### ISSUE THREAD

**Issue by MSE1188** [icarus-consulting/Yaapii.Atoms#322]
### Expected Behavior
Bow Action has a configurable interval to wait between each trigger call, which is 250 milliseconds by default
Exceptions in the task are thrown

### Actual Behavior
Bow action only waits 1 millisecond between testing the trigger function.
Exception inside the Bow Task are not thrown and remain unrecognized

**Comment by Meerownymous** [comment]
@MSE1188 Title could be adjusted, it would be better to write "Change BowAction interval"
