### ISSUE TITLE
Implement a Switch to hold an internal bool state

### ISSUE THREAD

**Issue by aveXcaesar** [icarus-consulting/Yaapii.Atoms#324]
### Expected Behavior

We have a `Switch()` object implementing `IToggle`
```csharp
public interface IToggle
    {
        bool IsOn();
        void Toggle();
    }
```

### Actual Behavior

We have no Atoms object.
A work around is to use a `List<bool>` as immutable member and hold the state at index 0

**Comment by Meerownymous** [comment]
This behaviour encourages low-performance code styles, so lets not put it into atoms.
