### ISSUE TITLE
MapEnvelope should use StickyScalar in secondary Ctor

### ISSUE THREAD

**Issue by ICACLE** [icarus-consulting/Yaapii.Atoms#335]
### Expected Behavior

A fast Map like .Net Dictionary

### Actual Behavior

Secondary ctor not usable! Map will be slow as hell because whole dictionary will be build for each access.

**Comment by Meerownymous** [comment]
This behaviour is intended, there is a class StickyMap which can be used when a map is needed that should not work as a live object.

**Comment by Meerownymous** [comment]
Closed because works as designed.
