### ISSUE TITLE
Create Each class which takes Action<T> and IEnumerable<T>

### ISSUE THREAD

**Issue by Meerownymous** [icarus-consulting/Yaapii.Atoms#36]
### Bug Report or Feature Request (mark with an x)
- [ ] bug report -> please search issues before submitting
- [ ] feature request

### Expected Behavior
~~And has a ctor accepting Action<> (C# Lambda) and IEnumerable<>. It is for executing the Action for all elements in the IEnumerable<>, its input is an element from the list.~~
We need a new class replacing Foreach() of LinQ
Action ctors has to be deleated out of `And` class

### Actual Behavior
~~Ctor is not there :(~~
No Class exists, but some ctors exist in and

### Mention any other details that might be useful

see #56
see #40

**Comment by ICACLE** [comment]
@Meerownymous Ctors seams to exist.
But in my opinion this is not an `And`!
In my Option this is a `Foreach` (like LinQ Foreach methode)!

**Comment by ICACLE** [comment]
Miro and i agreed that this is nothing for the And class. We should create a new Class `Each`
