### ISSUE TITLE
Add a FallbackMap which has a fallback on missing keys

### ISSUE THREAD

**Issue by EdJoPaTo** [icarus-consulting/Yaapii.Atoms#363]
### Expected Behavior

The Map.Envelop accepts a fallback function which is called when a requested key is not found within the Map.

The function gets the requested but unset key and returns a Value.

### Actual Behavior

When requesting an unset key an exception is thrown.

### Steps to reproduce the behavior

- Create a map without content
- Request a key from the map
- Exception is thrown

**Comment by Meerownymous** [comment]
@EdJoPaTo We should improve the titles. Please write the title as "What needs to be done in this issue". Currently, the title can be misleading because it can be read as "it is wrong that map envelope accepts a fallback function". Better title is "Add a map with fallback"
