### ISSUE TITLE
No String Contains found (with IgnoreCase)

### ISSUE THREAD

**Issue by ICACLE** [icarus-consulting/Yaapii.Atoms#37]
### Bug Report or Feature Request (mark with an x)
- [ ] bug report -> please search issues before submitting
- [x] feature request

### Expected Behavior

A class wich takes two strings and a bool (optional): inputValue, containingValue, ignoreCase
Returns true if 'inputValue' contains 'containingValue'.
Ignore case switch.

### Actual Behavior

Does not exist

### Mention any other details that might be useful

Replaces CLEs Extension method:
`public static bool Contains(this string value, StringComparison strComparison)`

**Comment by koeeenig** [comment]
PR #43 has been merged into master. Closing this issue.
