### ISSUE TITLE
Revert incompatible version changes

### ISSUE THREAD

**Issue by icaHWI** [icarus-consulting/Yaapii.Atoms#420]
### Expected Behavior
No incompatible changes are done in minor version updates

### Actual Behavior
Version 2.1.2 has a modified constructor in MapOf
```public MapOf(IEnumerable<IKvp> entries, bool rejectBuildingAllValues = true)```

### Mention any other details that might be useful
Move the bool rejectBuildingAllValues to another ctor

### The log given by the failure.

**Comment by Meerownymous** [comment]
@icaHWI Why is a default value considered an incompatible change? I see it as an improvement, as it does not break existing functionality?

**Comment by icaHWI** [comment]
@Meerownymous  Because the original constructor cant be found by a repository that references the lower version of the nuget.
