### ISSUE TITLE
ManyEnvelope is not sticky

### ISSUE THREAD

**Issue by MSE1188** [icarus-consulting/Yaapii.Atoms#425]
### Expected Behavior
Enumerable implementations should be sticky by default, but ManyEnvelope is not

### Mention any other details that might be useful
This test fails:
```csharp
[Fact]
        public void IsSticky()
        {
            var calls = 0;
            var list =
                new Filtered<string>(
                    (input) =>
                    {
                        calls++;
                        return input != "B";
                    },
                    new List<string>() { "A", "B", "C" }
                );
            new LengthOf(list).Value();
            new LengthOf(list).Value();
            Assert.Equal(
                3,
                calls
            );
        }
```

### The log given by the failure.

**Comment by Meerownymous** [comment]
ManyEnvelope (using live: false) is sticky but not like most users expect: While the main Enumerable object is indeed sticky, its contents may differ each time the enumerator is generated.
This led to confusion so the design will be changed: The items are sticky, so every iteration will give the same results.
