### ISSUE TITLE
List.Contains does not work

### ISSUE THREAD

**Issue by MSE1188** [icarus-consulting/Yaapii.Atoms#460]
### Expected Behavior
ListEnvelope Contains method works

### Actual Behavior
The following code throws an index out of range exception
```csharp
[Fact]
public void Test()
{
  var list = new ListOf<string>();
  Assert.False(list.Contains("item"));
}
```
The problem comes from ```ListEnvelope```, which uses a cached enumator. This enumerators ```ContainsKey``` method returns true, even if the key does not exist.

### The log given by the failure.

**Comment by Meerownymous** [comment]
closed via #461
