### ISSUE TITLE
SubText signature wrong

### ISSUE THREAD

**Issue by aveXcaesar** [icarus-consulting/Yaapii.Atoms#465]
### Expected Behavior
Ctor works as described:
https://github.com/icarus-consulting/Yaapii.Atoms/blob/1486388e690acb456ed6057fa1550b7871c438f7/src/Yaapii.Atoms/Text/SubText.cs#L47

### Actual Behavior
The ctor signature is wrong. The parameter `end` has the functionality of a length.
Rename variable name from `end` to `len` or calculate the length from `strt` and `end`.

### Mention any other details that might be useful
Consider additional info in #502 

### The log given by the failure.

**Comment by Meerownymous** [comment]
Renaming parameter should do it and is less invasive. 
Then it is no breaking change.
