### ISSUE TITLE
Library version in nuget Package is wrong

### ISSUE THREAD

**Issue by aveXcaesar** [icarus-consulting/Yaapii.Atoms#475]
### Expected Behavior
For all target frameworks the library version is set correct.

### Actual Behavior
The current NuGet (v2.2.2) delivers two target frameworks containing the Yaapii.Atoms.dll:
- net45: Yaapii.Atoms.dll v2.2.2.0
- netstandard2.0: Yaapii.Atoms.dll v1.0.0.0 but should be v2.2.2.0

### The log given by the failure.

**Comment by koeeenig** [comment]
I can confirm this is an issue using the library in a .NET 6 project as well.

**Comment by aveXcaesar** [comment]
@koeeenig 
I think so too.
I don't know the exact reason anymore. Probably a project did not build correctly during testing
