### ISSUE TITLE
Missing ctor for TextOf(double)

### ISSUE THREAD

**Issue by ICACLE** [icarus-consulting/Yaapii.Atoms#48]
### Bug Report or Feature Request (mark with an x)
- [ ] bug report -> please search issues before submitting
- [x] feature request

### Expected Behavior

I can make a Text of a double

### Actual Behavior

No possiblity to call 'new TextOf(Math.Pi)'

### Mention any other details that might be useful

To convert a double to a String it should be used '.ToString("G17")'. Not losing accuracy.

**Comment by Meerownymous** [comment]
https://msdn.microsoft.com/de-de/library/system.globalization.numberformatinfo.numberdecimalseparator(v=vs.110).aspx

**Comment by koeeenig** [comment]
merge into master at #61
