### ISSUE TITLE
Correct error message for ItemAt

### ISSUE THREAD

**Issue by pz1337** [icarus-consulting/Yaapii.Atoms#484]
### Expected Behavior
There is a logical error message in relation to index and count.

### Actual Behavior
There is an illogical error message.

### Mention any other details that might be useful
In the error message "position" and "item" are indices. They are counted form zero. Index "3" from the test should become a 4 in the message.
In the error message "items" is the count and can stay "3".

### Steps to reproduce the behavior
```
        [Fact]
        public void DeliversLogicErrorMessage()
        {
            try
            {
                new ItemAt<string>(
                    new string[] { "one", "two", "three" },
                    3
                ).Value();
            }
            catch (Exception ex)
            {
                Assert.Contains(
                    "4",
                    ex.Message
                );
            }
        }
```

### The log given by the failure.
'Cannot get element at position 3: Cannot get item 3 - The enumerable has only 3 items.'

**Comment by Meerownymous** [comment]
The test is not safe when no Exception occurs, it will pass then which is not correct.
