### ISSUE TITLE
Correct SubText variable names

### ISSUE THREAD

**Issue by pz1337** [icarus-consulting/Yaapii.Atoms#502]
### Expected Behavior
Changes are:
❗ end -> length
strt -> start
len -> length

### Actual Behavior
See Expected Behavior ⬆.

### Steps to reproduce the behavior
```
        [Fact]
        public void DeliversSubText()
        {
            Assert.Equal(
                "the_end",
                new SubText(
                    "this_is:the_end",
                    8,
                    14
                ).AsString()
            );
        }

```

### The log given by the failure.
System.ArgumentOutOfRangeException : Index and length must refer to a location within the string. (Parameter 'length')

**Comment by aveXcaesar** [comment]
Duplicate. See #465
