### ISSUE TITLE
Joined with first second and enum crashes out of index

### ISSUE THREAD

**Issue by jaanpeeter** [icarus-consulting/Yaapii.Atoms#543]
### Expected Behavior
We can use the ctor public Joined(T first, T second, IEnumerable<T> lst, params T[] items)

### Actual Behavior
It chrashes with index out of bounds

### Mention any other details that might be useful
 [Fact]
        public void JoinsFirstSecondAndEnum()
        {
            Assert.True(
                new LengthOf(
                    new Joined<string>(
                        "first",
                        "second",
                        new ManyOf<string>("third", "fourth")                       
                    )
                ).Value() == 4,
            "cannot join first second and enum together");
        }

### The log given by the failure.

**Comment by Meerownymous** [comment]
I suggest testing the correct order by joining the strings and putting an Assertion for the combined string.

**Comment by Meerownymous** [comment]
Solved with PR #555
