### ISSUE TITLE
Proposal: Sticky by default seems too expensive for enumerations, get rid of it?

### ISSUE THREAD

**Issue by Meerownymous** [icarus-consulting/Yaapii.Atoms#551]
Recent research [here](https://github.com/icarus-consulting/Yaapii.Atoms/pull/545) and [here](https://github.com/icarus-consulting/Yaapii.Atoms/issues/540), which was triggered by StackOverflow Exceptions made me think.

Some years ago, we switched the library design to "sticky by default". Back then, we noticed that developers were unaware that for example dictionaries were built again and again on each access to their data. The idea was that the developer does not have to think about caching, and that it is implemented by default into every object.

In the recent case, this design has revealed how expensive this is for Enumerations. The current implementation of 'ManyEnvelope' instantiates a Caching object. The assumption is that it is more performant for an Enumerator, if every visited item is put into a cache. If we think about objects like 'Mapped', where we transform things, this seems to be the right choice - the transformation will happen only once. The next time, when the item is accessed, the result from the previous transformation is returned.
Another thing that the cache takes care of is not producing any elements that have not been computed. It keeps track of the farthest that the enumerator has moved. 

But: The EO design makes heavy use of the decorator pattern. This means we put Enumerable into the ctor of another Enumerable, and another, and another. When we decorate objects in 10 layers, we will build 10 caches. Only the most shallow cache is finally used. All the other caches are allocating memory and copying objects, producing computation power but having no benefit from it.

And in addition to this, for most of the objects, no caching is needed as there is no chance that the contents can change.

I am thinking: Wouldn't it be better to remove the cache by default for enumerations and reintroduce a memoizing ob ject like we had before with 'Sticky'?

**LinQ**
In the discussion it was a thought that wrapping LinQ might be a better approach. I have done some analysis and found that LinQ is not faster or more advanced that what we can do with the Atoms objects. LinQ simply offers extension methods, which are static methods, that in their style decorate their input. 

In terms of caching, the React LinQ extensions offer an operator [Memoize](https://github.com/dotnet/reactive/blob/9fb0ed0d0160902ca550c44f6d2f89f54b0b53c7/Ix.NET/Source/System.Interactive/System/Linq/Operators/Memoize.cs)', which is quite similar to the caching object in Atoms. It uses an object called 'MemoizedBuffer' to keep track of the already enumerated items. The difference is only that LinQ is a procedural approach compared to the object approach here. Internally, it wraps enumerables into new objects, sometimes using the decorator pattern  directly and sometimes using yield, which is syntactic sugar and results in a decorator built by the compiler. 

If we would use LinQ, what we currently do in this library is something like this:

```
    items.Select(item => transform(item))
    .Memoize()
    .Where(item => filter(item)
    .Memoize()
    .Select(nextTransform)
    .Memoize()
```

I think default caching could be removed for most enumerables and a noticeable performance gain will be the result.

**Comment by MSE1188** [comment]
I see that. Most easy way would be to invert the ```live``` flags to ```true```, then the cache in the envelope will never be touched. Then add the StickyList again...
As our other libraries are currently on the assumption of the lists being sticky by default, this would mean a lot of refactoring, I will discuss with the team

**Comment by Meerownymous** [comment]
Heavy refactoring seems costly and might not be necessary. I think a middle way - backwards compatible - would be to let objects with more load remain sticky (mapped, filtered etc) but remove the sticky behaviour from the ones which do not profit from it in everyday scenarios. 

Joined is an example where I am not sure what stickyness is of an advantage.

**Comment by MSE1188** [comment]
Sounds reasonable. I will have a look where else we can remove the sticky behaviour

**Comment by MSE1188** [comment]
thank you! I created a Pull Request from this and will take a look into this in the next days

**Comment by Meerownymous** [comment]
Closing: Decision is to not change the default behaviour, but remove stickyness from objects where it has no benefit.
