### ISSUE TITLE
Fails should accept a specific Exception in ctor

### ISSUE THREAD

**Issue by Meerownymous** [icarus-consulting/Yaapii.Atoms#58]
### Bug Report or Feature Request (mark with an x)
- [ ] bug report -> please search issues before submitting
- [x] feature request

### Expected Behavior
We can inject a specific Exception into a ctor of a fail so that it gets thrown.

### Actual Behavior
We cannot inject specific Exceptions into ctor

**Comment by ICACLE** [comment]
@Meerownymous Does `public FailAlways(Exception error)` doesn't fulfil your request?

**Comment by Meerownymous** [comment]
FailAlways is a class that will always fail, with the given Exception, when you call Go()... 

What I had in mind was the ability to tell a fail which Exception it should throw if failing, but not fail always.
