### ISSUE TITLE
Nuget missing in Github releases

### ISSUE THREAD

**Issue by Meerownymous** [icarus-consulting/Yaapii.Atoms#73]
### Bug Report or Feature Request (mark with an x)
- [x] bug report -> please search issues before submitting
- [ ] feature request

### Expected Behavior
Release feed has Nuget package

### Actual Behavior
Release feed has no Nuget package

**Comment by aveXcaesar** [comment]
Is it currently solved?

**Comment by aveXcaesar** [comment]
Close issue because it is obsolete
