### ISSUE TITLE
Replace new modifier of Methods

### ISSUE THREAD

**Issue by ICACLE** [icarus-consulting/Yaapii.Atoms#75]
### Bug Report or Feature Request (mark with an x)
- [x] bug report -> please search issues before submitting
- [ ] feature request

### Expected Behavior

Calling a method of an interface or .net class will execute the code of the methods marked with new, yet.
But it will be executed the base class methode code...

### Actual Behavior

The new modifier was used like a override...

### Mention any other details that might be useful

I replaced it for the Method 'Dispose()'
I saw the StickyList uses a lot of them.

**Comment by Meerownymous** [comment]
integrated in #77
