### ISSUE TITLE
Extend Sticky classes by Clear/Reset Method (refactor)

### ISSUE THREAD

**Issue by ICACLE** [icarus-consulting/Yaapii.Atoms#76]
### Bug Report or Feature Request (mark with an x)
- [ ] bug report -> please search issues before submitting
- [x] feature request

### Expected Behavior

Have a methode to clear cache.

### Actual Behavior

sticky classes get only a reload condiction ctor by #70 

### Mention any other details that might be useful

see also #71

**Comment by Meerownymous** [comment]
I think we do not need this feature.
